# Generated by Django 5.0.14 on 2026-04-21 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='organization',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Organization Name'),
        ),
    ]
